[2023-12-04T14:05:36.661+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T14:05:36.668+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T14:05:36.668+0000] {taskinstance.py:1359} INFO - Starting attempt 4 of 4
[2023-12-04T14:05:36.681+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): copying_file> on 2023-11-30 21:10:00+00:00
[2023-12-04T14:05:36.686+0000] {standard_task_runner.py:57} INFO - Started process 5591 to run task
[2023-12-04T14:05:36.689+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'copying_file', 'scheduled__2023-11-30T21:10:00+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpokchq4q3']
[2023-12-04T14:05:36.690+0000] {standard_task_runner.py:85} INFO - Job 93: Subtask copying_file
[2023-12-04T14:05:36.728+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [running]> on host ed47267dc344
[2023-12-04T14:05:36.785+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='copying_file' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T21:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-30T21:10:00+00:00'
[2023-12-04T14:05:36.787+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T14:05:36.788+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cp kaggle.json ~/.kaggle/']
[2023-12-04T14:05:36.799+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T14:05:36.808+0000] {subprocess.py:93} INFO - cp: cannot stat 'kaggle.json': No such file or directory
[2023-12-04T14:05:36.809+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-04T14:05:36.817+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-04T14:05:36.820+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=Georgy, task_id=copying_file, execution_date=20231130T211000, start_date=20231204T140536, end_date=20231204T140536
[2023-12-04T14:05:36.833+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 93 for task copying_file (Bash command failed. The command returned a non-zero exit code 1.; 5591)
[2023-12-04T14:05:36.862+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-04T14:05:36.886+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
