[2023-12-04T13:05:32.790+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T13:05:32.796+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T13:05:32.797+0000] {taskinstance.py:1359} INFO - Starting attempt 3 of 4
[2023-12-04T13:05:32.808+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): copying_file> on 2023-11-30 21:10:00+00:00
[2023-12-04T13:05:32.813+0000] {standard_task_runner.py:57} INFO - Started process 4662 to run task
[2023-12-04T13:05:32.816+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'copying_file', 'scheduled__2023-11-30T21:10:00+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpop3faqki']
[2023-12-04T13:05:32.817+0000] {standard_task_runner.py:85} INFO - Job 92: Subtask copying_file
[2023-12-04T13:05:32.859+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [running]> on host ed47267dc344
[2023-12-04T13:05:32.914+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='copying_file' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T21:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-30T21:10:00+00:00'
[2023-12-04T13:05:32.915+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T13:05:32.916+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cp kaggle.json ~/.kaggle/']
[2023-12-04T13:05:32.927+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T13:05:32.948+0000] {subprocess.py:93} INFO - cp: cannot stat 'kaggle.json': No such file or directory
[2023-12-04T13:05:32.949+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-04T13:05:32.958+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-04T13:05:32.961+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=Georgy, task_id=copying_file, execution_date=20231130T211000, start_date=20231204T130532, end_date=20231204T130532
[2023-12-04T13:05:32.978+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 92 for task copying_file (Bash command failed. The command returned a non-zero exit code 1.; 4662)
[2023-12-04T13:05:32.987+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-04T13:05:33.011+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
