[2023-12-04T14:05:51.915+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.copying_file manual__2023-12-04T11:05:15.213969+00:00 [queued]>
[2023-12-04T14:05:51.923+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.copying_file manual__2023-12-04T11:05:15.213969+00:00 [queued]>
[2023-12-04T14:05:51.923+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-04T14:05:51.934+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): copying_file> on 2023-12-04 11:05:15.213969+00:00
[2023-12-04T14:05:51.939+0000] {standard_task_runner.py:57} INFO - Started process 5615 to run task
[2023-12-04T14:05:51.942+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'copying_file', 'manual__2023-12-04T11:05:15.213969+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp5xxeydqv']
[2023-12-04T14:05:51.943+0000] {standard_task_runner.py:85} INFO - Job 97: Subtask copying_file
[2023-12-04T14:05:51.979+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.copying_file manual__2023-12-04T11:05:15.213969+00:00 [running]> on host ed47267dc344
[2023-12-04T14:05:52.033+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='copying_file' AIRFLOW_CTX_EXECUTION_DATE='2023-12-04T11:05:15.213969+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-04T11:05:15.213969+00:00'
[2023-12-04T14:05:52.034+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T14:05:52.036+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cp kaggle.json ~/.kaggle/']
[2023-12-04T14:05:52.045+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T14:05:52.048+0000] {subprocess.py:93} INFO - cp: cannot stat 'kaggle.json': No such file or directory
[2023-12-04T14:05:52.048+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-04T14:05:52.056+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-04T14:05:52.059+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=Georgy, task_id=copying_file, execution_date=20231204T110515, start_date=20231204T140551, end_date=20231204T140552
[2023-12-04T14:05:52.068+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 97 for task copying_file (Bash command failed. The command returned a non-zero exit code 1.; 5615)
[2023-12-04T14:05:52.114+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-04T14:05:52.135+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
